import { Link } from "react-router-dom";
import Footer from "../components/Footer";

export default function Terms() {
  const lastUpdated = "February 17, 2026";
  const contactEmail = "support@develevator.com";

  return (
    <div className="min-h-screen bg-[#0d1117] text-slate-300 font-sans">
      {/* Simple Header */}
      <div className="border-b border-white/5 bg-[#161b22]">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center">
          <span className="font-bold text-lg text-slate-100">
            <Link to="/">DevElevator</Link>
          </span>
          <span className="mx-3 text-slate-600">/</span>
          <span className="font-medium text-slate-400">Terms of Service</span>
        </div>
      </div>

      {/* Legal Content */}
      <main className="max-w-4xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-slate-500 mb-8">Last Updated: {lastUpdated}</p>

        <div className="space-y-8 text-sm leading-relaxed text-slate-300">
          {/* 1. Acceptance */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using DevElevator ("Service"), you agree to be
              bound by these Terms of Service ("Terms"). If you disagree with
              any part of the terms, you may not access the Service.
            </p>
          </section>

          {/* 2. Description of Service */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">
              2. Description of Service
            </h2>
            <p>
              DevElevator is an AI-powered developer tool that allows users to
              index their GitHub repositories and query them using natural
              language. The Service uses third-party Artificial Intelligence
              (AI) providers to generate responses and code snippets.
            </p>
          </section>

          {/* 3. AI Disclaimer (CRITICAL FOR DEV TOOLS) */}
          <section className="bg-red-500/5 border border-red-500/20 p-4 rounded-lg">
            <h2 className="text-lg font-semibold text-red-200 mb-2">
              3. AI Accuracy & Liability Disclaimer
            </h2>
            <p className="mb-2">
              <strong>The Service uses experimental AI technology.</strong>{" "}
              Responses generated by DevElevator:
            </p>
            <ul className="list-disc pl-5 space-y-1 mb-2">
              <li>May contain errors, bugs, or security vulnerabilities.</li>
              <li>
                Should <strong>never</strong> be deployed to production
                environments without thorough human review and testing.
              </li>
              <li>Are provided "as is" without warranty of any kind.</li>
            </ul>
            <p>
              <strong>You are solely responsible</strong> for any code you
              write, copy, or deploy based on suggestions from the Service.
              DevElevator is not liable for any system outages, data loss, or
              security breaches resulting from the use of generated code.
            </p>
          </section>

          {/* 4. Intellectual Property */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">
              4. Intellectual Property Rights
            </h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong>Your Code:</strong> You retain all rights and ownership
                of the code repositories you connect to the Service. We do not
                claim ownership of your intellectual property.
              </li>
              <li>
                <strong>Our Platform:</strong> DevElevator, including its
                interface, proprietary indexing logic, and branding, is owned by
                us and protected by copyright laws.
              </li>
              <li>
                <strong>AI Output:</strong> To the fullest extent permitted by
                law, you own the output generated by the AI in response to your
                queries.
              </li>
            </ul>
          </section>

          {/* 5. Acceptable Use */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">
              5. Acceptable Use
            </h2>
            <p>
              You agree not to misuse the Service. Prohibited actions include:
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>
                Reverse engineering or attempting to extract our source code.
              </li>
              <li>
                Using the Service to generate malicious code, malware, or
                viruses.
              </li>
              <li>
                Overloading our infrastructure (e.g., DDoS attacks or abusive
                API scraping).
              </li>
              <li>Sharing your account credentials with multiple users.</li>
            </ul>
          </section>

          {/* 6. Limitation of Liability */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">
              6. Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, DevElevator shall not be
              liable for any indirect, incidental, special, consequential, or
              punitive damages, including without limitation, loss of profits,
              data, use, goodwill, or other intangible losses, resulting from
              your access to or use of the Service.
            </p>
          </section>

          {/* 7. Termination */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">
              7. Termination
            </h2>
            <p>
              We may terminate or suspend your account immediately, without
              prior notice or liability, for any reason whatsoever, including
              without limitation if you breach the Terms. Upon termination, your
              right to use the Service will cease immediately.
            </p>
          </section>

          {/* 8. Contact */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">
              8. Contact Us
            </h2>
            <p>
              If you have any questions about these Terms, please contact us at:
              <br />
              <a
                href={`mailto:${contactEmail}`}
                className="text-primary hover:underline mt-1 block">
                {contactEmail}
              </a>
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
