import { useState, useEffect } from "react";
import {
  X,
  GitPullRequest,
  Check,
  Loader2,
  ArrowRight,
  FileDiff,
  RefreshCw,
} from "lucide-react";
import axios, { AxiosError } from "axios";
import ReactDiffViewer, { DiffMethod } from "react-diff-viewer-continued";

interface PRModalProps {
  isOpen: boolean;
  onClose: () => void;
  projectId: string;
  filePath: string;
  newContent: string;
}

interface ApiErrorResponse {
  error: string;
}

interface ApiSuccessResponse {
  success: boolean;
  prUrl: string;
}

export default function PRModal({
  isOpen,
  onClose,
  projectId,
  filePath,
  newContent,
}: PRModalProps) {
  const [step, setStep] = useState<
    "loading_diff" | "diff" | "form" | "submitting" | "success"
  >("loading_diff");

  // State for the file path (Editable)
  const [targetPath, setTargetPath] = useState(filePath);

  const [originalContent, setOriginalContent] = useState("");
  const [prUrl, setPrUrl] = useState<string>("");
  const [error, setError] = useState<string>("");

  const [formData, setFormData] = useState({
    title: "",
    description: "This PR was generated by DevElevator AI.",
    branch: "",
  });

  // Reset state when modal opens
  useEffect(() => {
    if (isOpen) {
      setTargetPath(filePath); // Reset to default
      fetchOriginalContent(filePath); // Fetch immediately

      // Reset form data
      setFormData({
        title: `Fix: Update ${filePath.split("/").pop()}`,
        description: "This PR was generated by DevElevator AI.",
        branch: `ai-fix-${Date.now()}`,
      });
    }
  }, [isOpen, filePath]);

  // Function to fetch original content
  const fetchOriginalContent = async (path: string) => {
    setStep("loading_diff");
    try {
      const { data } = await axios.get(
        `${import.meta.env.VITE_API_URL}/api/projects/${projectId}/file?path=${encodeURIComponent(path)}`,
        { withCredentials: true },
      );
      setOriginalContent(data.content || "");
    } catch (err) {
      // If 404, it means new file. Empty string is correct.
      console.error("Failed to load original content", err);
      setOriginalContent("");
    } finally {
      setStep("diff");
    }
  };

  const handlePathBlur = () => {
    // When user leaves the input field, refresh the diff
    if (targetPath.trim() !== "") {
      fetchOriginalContent(targetPath);
      // Also update the default title/branch to match new filename
      setFormData((prev) => ({
        ...prev,
        title: `Fix: Update ${targetPath.split("/").pop()}`,
      }));
    }
  };

  if (!isOpen) return null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setStep("submitting");
    setError("");

    try {
      const response = await axios.post<ApiSuccessResponse>(
        `${import.meta.env.VITE_API_URL}/api/github/pr`,
        {
          projectId,
          filePath: targetPath, // 👈 Send the EDITED path, not the prop
          newContent,
          prTitle: formData.title,
          prDescription: formData.description,
          branchName: formData.branch,
        },
        { withCredentials: true },
      );

      if (response.data.success) {
        setPrUrl(response.data.prUrl);
        setStep("success");
      }
    } catch (err: unknown) {
      if (axios.isAxiosError(err)) {
        const axiosError = err as AxiosError<ApiErrorResponse>;
        setError(axiosError.response?.data?.error || "Failed to create PR");
      } else if (err instanceof Error) {
        setError(err.message);
      } else {
        setError("An unexpected error occurred");
      }
      setStep("form");
    }
  };

  const renderDiff = () => (
    <div className="max-h-[60vh] overflow-y-auto rounded-lg border border-white/10 bg-[#0d1117] text-xs">
      <ReactDiffViewer
        oldValue={originalContent}
        newValue={newContent}
        splitView={true}
        compareMethod={DiffMethod.WORDS}
        useDarkTheme={true}
        styles={{
          variables: {
            dark: {
              diffViewerBackground: "#0d1117",
              diffViewerTitleBackground: "#161b22",
              gutterBackground: "#0d1117",
              gutterBackgroundDark: "#0d1117",
              gutterColor: "#484f58",
              addedBackground: "#2ea04326",
              removedBackground: "#da363326",
              wordAddedBackground: "#2ea04366",
              wordRemovedBackground: "#da363366",
            },
          },
          line: { padding: "2px 0" },
        }}
      />
    </div>
  );

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div
        className={`bg-[#161b22] border border-white/10 rounded-xl w-full shadow-2xl overflow-hidden transition-all duration-300 ${step === "diff" || step === "loading_diff" ? "max-w-6xl" : "max-w-lg"}`}>
        {/* Header */}
        <div className="flex justify-between items-center p-4 border-b border-white/10 bg-[#0d1117]">
          <h3 className="text-white font-semibold flex items-center gap-2">
            {step === "diff" || step === "loading_diff" ? (
              <FileDiff className="w-5 h-5 text-blue-400" />
            ) : (
              <GitPullRequest className="w-5 h-5 text-purple-400" />
            )}
            {step.includes("diff") ? "Review Changes" : "Create Pull Request"}
          </h3>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-white transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-6">
          {/* -------------------------------------------------- */}
          {/* NEW: Global "Target File" Input (Always Visible)   */}
          {/* -------------------------------------------------- */}
          <div className="mb-6">
            <label className="block text-xs font-medium text-slate-400 mb-1">
              Target File Path
            </label>
            <div className="relative group">
              <input
                type="text"
                value={targetPath}
                onChange={(e) => setTargetPath(e.target.value)}
                onBlur={handlePathBlur} // Fetch new diff when user leaves field
                onKeyDown={(e) => e.key === "Enter" && handlePathBlur()}
                className="w-full bg-[#0d1117] border border-white/10 rounded p-2 text-sm text-yellow-300 font-mono focus:ring-1 focus:ring-blue-500 outline-none transition-all pr-10"
                placeholder="src/components/MyComponent.tsx"
              />
              <button
                onClick={handlePathBlur}
                className="absolute right-2 top-2 text-slate-500 hover:text-white"
                title="Refresh Diff">
                <RefreshCw className="w-4 h-4" />
              </button>
            </div>
            <p className="text-[10px] text-slate-500 mt-1">
              Edit path and press Enter to reload the diff comparison.
            </p>
          </div>

          {/* STATE: LOADING DIFF */}
          {step === "loading_diff" && (
            <div className="flex flex-col items-center justify-center py-12">
              <Loader2 className="w-10 h-10 text-blue-500 animate-spin mb-4" />
              <p className="text-slate-400">Fetching original file...</p>
            </div>
          )}

          {/* STATE: DIFF VIEWER */}
          {step === "diff" && (
            <div className="space-y-4">
              {renderDiff()}
              <div className="flex justify-end pt-4 gap-3">
                <button
                  onClick={onClose}
                  className="px-4 py-2 text-sm text-slate-300 hover:text-white">
                  Cancel
                </button>
                <button
                  onClick={() => setStep("form")}
                  className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-md text-sm font-medium transition-colors flex items-center gap-2">
                  Looks Good <ArrowRight className="w-4 h-4" />
                </button>
              </div>
            </div>
          )}

          {/* STATE: FORM & SUBMITTING */}
          {(step === "form" || step === "submitting") && (
            <form
              onSubmit={handleSubmit}
              className="space-y-4">
              {step === "submitting" ? (
                <div className="flex flex-col items-center justify-center py-8">
                  <Loader2 className="w-12 h-12 text-purple-500 animate-spin mb-4" />
                  <p className="text-slate-300">Pushing to GitHub...</p>
                </div>
              ) : (
                <>
                  {error && (
                    <div className="p-3 bg-red-500/10 border border-red-500/20 rounded text-red-200 text-sm">
                      {error}
                    </div>
                  )}

                  <div>
                    <label className="block text-xs font-medium text-slate-400 mb-1">
                      PR Title
                    </label>
                    <input
                      type="text"
                      required
                      value={formData.title}
                      onChange={(e) =>
                        setFormData((prev) => ({
                          ...prev,
                          title: e.target.value,
                        }))
                      }
                      className="w-full bg-[#0d1117] border border-white/10 rounded p-2 text-sm text-white focus:ring-1 focus:ring-purple-500 outline-none transition-all"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-medium text-slate-400 mb-1">
                      Branch Name
                    </label>
                    <input
                      type="text"
                      required
                      value={formData.branch}
                      onChange={(e) =>
                        setFormData((prev) => ({
                          ...prev,
                          branch: e.target.value,
                        }))
                      }
                      className="w-full bg-[#0d1117] border border-white/10 rounded p-2 text-sm text-white font-mono focus:ring-1 focus:ring-purple-500 outline-none transition-all"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-medium text-slate-400 mb-1">
                      Description
                    </label>
                    <textarea
                      value={formData.description}
                      onChange={(e) =>
                        setFormData((prev) => ({
                          ...prev,
                          description: e.target.value,
                        }))
                      }
                      className="w-full bg-[#0d1117] border border-white/10 rounded p-2 text-sm text-white h-20 focus:ring-1 focus:ring-purple-500 outline-none resize-none transition-all"
                    />
                  </div>

                  <div className="pt-2 flex justify-between">
                    <button
                      type="button"
                      onClick={() => setStep("diff")}
                      className="text-slate-400 hover:text-white text-sm">
                      ← Back to Review
                    </button>
                    <div className="flex gap-3">
                      <button
                        type="button"
                        onClick={onClose}
                        className="px-4 py-2 text-sm text-slate-300 hover:text-white">
                        Cancel
                      </button>
                      <button
                        type="submit"
                        className="bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded-md text-sm font-medium transition-colors flex items-center gap-2">
                        <GitPullRequest className="w-4 h-4" /> Create PR
                      </button>
                    </div>
                  </div>
                </>
              )}
            </form>
          )}

          {/* STATE: SUCCESS */}
          {step === "success" && (
            <div className="text-center py-6">
              <div className="mx-auto w-12 h-12 bg-green-500/20 rounded-full flex items-center justify-center mb-4">
                <Check className="w-6 h-6 text-green-400" />
              </div>
              <h4 className="text-white text-lg font-medium mb-2">
                PR Created Successfully!
              </h4>
              <p className="text-slate-400 text-sm mb-6">
                Your code has been pushed to a new branch and the PR is ready.
              </p>
              <a
                href={prUrl}
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center gap-2 bg-[#238636] hover:bg-[#2ea043] text-white px-4 py-2 rounded-md font-medium transition-colors">
                View on GitHub
              </a>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
